import { Inter, Fredoka } from "next/font/google";
import "./globals.css";
import Provider from "@/lib/provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="forest">
      <Provider>
        <body
          className={`${inter.variable} ${fredoka.variable} antialiased min-h-screen`}
        >
          {children}
        </body>
      </Provider>
    </html>
  );
}
